west.yml: use https instead of ssh
golioth/reference-design-template pull request #50
Opened 2023-08-28 01:37 UTC by szczys

Use publicly available https for cloning dependencies:

* golioth-zephyr-boards
* libostentus

2023-08-28 04:04 UTC, beriberikix approved these changes
Tested in VM - worked for me!

2023-08-28 04:07 UTC, beriberikix requested changes
Whoops! Need to delete the trailing `.git`

2023-08-28 14:25 UTC, szczys commented
Ah, you're right I've force-pushed the change, please take a look.

2023-08-28 15:03 UTC, cdwilson commented
@beriberikix not suggesting we should change this, but just curious, was there an issue you found with the `.git` suffix? GitHub's clone menu includes the `.git` but AFAIK it should work with or without it

<img width="1728" alt="image" src="https://github.com/golioth/reference-design-template/assets/14631/47c09274-2e7f-4fd9-9a9b-0e91dc87f02c">

2023-08-28 15:08 UTC, beriberikix commented
Ah, you know what? I may have been testing a few things and it could work. Also force of habit 😉

2023-08-29 17:48 UTC, beriberikix commented
I've tested and both work! Should we keep .git or strip it to be consistent?

2023-08-29 21:13 UTC, szczys commented
I'm fine keeping it consistent (no .git)

2023-08-29 21:41 UTC, beriberikix approved these changes

2023-08-31 02:41 UTC, merged